---@meta
-- GENERATED by tools/Gen-Bindings.ps1 - editor stubs, never executed.
---@class s1
s1 = {}

---@class s1_apps_canvas
s1.apps_canvas = {}
function s1.apps_canvas.set_is_open(o) end
function s1.apps_canvas.is_open() end

---@class s1_arrest_notice_screen
s1.arrest_notice_screen = {}
function s1.arrest_notice_screen.exit() end
function s1.arrest_notice_screen.open() end
function s1.arrest_notice_screen.record_crimes() end
function s1.arrest_notice_screen.is_open() end

---@class s1_arrest_screen
s1.arrest_screen = {}
function s1.arrest_screen.open() end
function s1.arrest_screen.close() end
function s1.arrest_screen.is_open() end

---@class s1_audio
s1.audio = {}
function s1.audio.set_distorted(distorted, transition) end
function s1.audio.set_master_volume(volume) end
function s1.audio.master_volume() end

---@class s1_birds_eye_view
s1.birds_eye_view = {}
function s1.birds_eye_view.disable(reenableCameraLook) end
function s1.birds_eye_view.is_enabled() end

---@class s1_blackjack_interface
s1.blackjack_interface = {}
function s1.blackjack_interface.close() end

---@class s1_black_overlay
s1.black_overlay = {}
function s1.black_overlay.open(fadeTime) end
function s1.black_overlay.close(fadeTime) end
function s1.black_overlay.is_shown() end

---@class s1_body_search_screen
s1.body_search_screen = {}
function s1.body_search_screen.close(clear) end
function s1.body_search_screen.close_tutorial() end
function s1.body_search_screen.is_open() end
function s1.body_search_screen.tutorial_open() end

---@class s1_brick_press_canvas
s1.brick_press_canvas = {}
function s1.brick_press_canvas.close() end
function s1.brick_press_canvas.begin_button_pressed() end

---@class s1_build
s1.build = {}
function s1.build.stop_building() end
function s1.build.is_building() end

---@class s1_business
s1.business = {}
function s1.business.delete_unapproved_files(parentFolderPath) end

---@class s1_call_interface
s1.call_interface = {}
function s1.call_interface.complete_call() end
function s1.call_interface.continue() end
function s1.call_interface.is_open() end

---@class s1_call
s1.call = {}
function s1.call.clear_queued_call() end

---@class s1_call_notification
s1.call_notification = {}
function s1.call_notification.is_open() end

---@class s1_cartel
s1.cartel = {}
function s1.cartel.set_status_server(status, resetStatusChangedTimer) end
function s1.cartel.status() end
function s1.cartel.hours_since_status_change() end

---@class s1_cauldron_interface
s1.cauldron_interface = {}
function s1.cauldron_interface.close() end
function s1.cauldron_interface.begin_button_pressed() end

---@class s1_character_creator
s1.character_creator = {}
function s1.character_creator.close() end
function s1.character_creator.disable_stuff() end
function s1.character_creator.done() end
function s1.character_creator.slider_changed(newVal) end
function s1.character_creator.select_preset(presetName) end
function s1.character_creator.refresh_category(category) end
function s1.character_creator.is_open() end

---@class s1_character_display
s1.character_display = {}
function s1.character_display.set_open(open) end
function s1.character_display.is_open() end

---@class s1_checkpoint
s1.checkpoint = {}
function s1.checkpoint.set_checkpoint_enabled(checkpoint, enabled, requestedOfficers) end

---@class s1_chemistry_station_interface
s1.chemistry_station_interface = {}
function s1.chemistry_station_interface.close() end

---@class s1_compass
s1.compass = {}
function s1.compass.set_compass_enabled(enabled) end
function s1.compass.set_visible(visible) end

---@class s1_config
s1.config = {}
function s1.config.is_srp_batcher_supported() end
function s1.config.get_actual_rendering_mode(shaderMode) end
function s1.config.force_update_fade_out_camera() end
function s1.config.get_raymarching_quality_index_for_unique_id(id) end
function s1.config.is_raymarching_quality_unique_id_valid(id) end
function s1.config.reset() end
function s1.config.reset_internal_data() end
function s1.config.render_pipeline() end
function s1.config.rendering_mode() end
function s1.config.sd_use_single_pass_shader() end
function s1.config.sd_requires_double_sided_mesh() end
function s1.config.default_raymarching_quality_unique_id() end
function s1.config.raymarching_qualities_count() end
function s1.config.is_hdrp_exposure_weight_supported() end
function s1.config.has_render_pipeline_mismatch() end

---@class s1_contacts_app
s1.contacts_app = {}
function s1.contacts_app.set_selected_region(region, selectNPC) end
function s1.contacts_app.set_open(open) end

---@class s1_curfew
s1.curfew = {}
function s1.curfew.disable() end
function s1.curfew.is_enabled() end
function s1.curfew.is_currently_active() end
function s1.curfew.is_hard_curfew_active() end

---@class s1_cursor
s1.cursor = {}
function s1.cursor.set_cursor_appearance(type) end

---@class s1_customization
s1.customization = {}
function s1.customization.create_settings(assetName, assetPath) end
function s1.customization.load_settings(path, editOriginal) end
function s1.customization.gender_changed(genderScale) end
function s1.customization.weight_changed(weightScale) end
function s1.customization.height_changed(height) end
function s1.customization.upper_eye_lid_resting_position_changed(newVal) end
function s1.customization.lower_eye_lid_resting_position_changed(newVal) end
function s1.customization.eyebrow_scale_changed(newVal) end
function s1.customization.eyebrow_thickness_changed(newVal) end
function s1.customization.eyebrow_resting_height_changed(newVal) end
function s1.customization.eyebrow_resting_angle_changed(newVal) end
function s1.customization.pupil_dilation_changed(dilation) end

---@class s1_cutscene
s1.cutscene = {}
function s1.cutscene.play(name) end

---@class s1_daily_summary
s1.daily_summary = {}
function s1.daily_summary.open() end
function s1.daily_summary.close() end
function s1.daily_summary.add_sold_item(id, amount) end
function s1.daily_summary.add_player_money(amount) end
function s1.daily_summary.add_dealer_money(amount) end
function s1.daily_summary.add_xp(xp) end
function s1.daily_summary.is_open() end
function s1.daily_summary.xp_gained() end

---@class s1_dark_market
s1.dark_market = {}
function s1.dark_market.send_unlocked() end
function s1.dark_market.is_open() end
function s1.dark_market.unlocked() end

---@class s1_deal_completion_popup
s1.deal_completion_popup = {}
function s1.deal_completion_popup.is_playing() end

---@class s1_dealer_management_app
s1.dealer_management_app = {}
function s1.dealer_management_app.refresh() end
function s1.dealer_management_app.set_open(open) end
function s1.dealer_management_app.assign_customer() end

---@class s1_death_screen
s1.death_screen = {}
function s1.death_screen.open() end
function s1.death_screen.close() end

---@class s1_delivery_app
s1.delivery_app = {}
function s1.delivery_app.set_open(open) end
function s1.delivery_app.play_order_submitted_anim() end

---@class s1_dialogue_canvas
s1.dialogue_canvas = {}
function s1.dialogue_canvas.is_open() end
function s1.dialogue_canvas.skip_next_rollout() end

---@class s1_document_viewer
s1.document_viewer = {}
function s1.document_viewer.open(documentName) end
function s1.document_viewer.close() end
function s1.document_viewer.is_open() end

---@class s1_drag
s1.drag = {}
function s1.drag.fixed_update() end
function s1.drag.is_dragging_allowed() end
function s1.drag.is_dragging() end

---@class s1_drying_rack_interface
s1.drying_rack_interface = {}
function s1.drying_rack_interface.close() end
function s1.drying_rack_interface.insert() end

---@class s1_employee
s1.employee = {}
function s1.employee.register_name(name) end
function s1.employee.register_appearance(male, index) end

---@class s1_environment_fx
s1.environment_fx = {}
function s1.environment_fx.set_environment_scrolling_active(active) end
function s1.environment_fx.set_environment_scrolling_speed_by_percentage(percentage) end
function s1.environment_fx.normalized_environmental_brightness() end
function s1.environment_fx.fog_end_distance_multiplier() end

---@class s1_environment
s1.environment = {}
function s1.environment.set_weather(type) end
function s1.environment.trigger_lightning_event() end
function s1.environment.trigger_distant_thunder() end

---@class s1_equippable_trash_grabber
s1.equippable_trash_grabber = {}
function s1.equippable_trash_grabber.unequip() end
function s1.equippable_trash_grabber.get_capacity() end
function s1.equippable_trash_grabber.is_equipped() end

---@class s1_eyelid_overlay
s1.eyelid_overlay = {}
function s1.eyelid_overlay.set_open(openness) end

---@class s1_fullscreen_fade
s1.fullscreen_fade = {}
function s1.fullscreen_fade.show() end
function s1.fullscreen_fade.hide() end
function s1.fullscreen_fade.is_open() end

---@class s1_game_input
s1.game_input = {}
function s1.game_input.get_button(buttonCode) end
function s1.game_input.get_button_down(buttonCode) end
function s1.game_input.get_button_up(buttonCode) end
function s1.game_input.get_current_input_device_is_keyboard_mouse() end
function s1.game_input.get_current_input_device_is_gamepad() end
function s1.game_input.get_current_input_device() end
function s1.game_input.exit_all() end
function s1.game_input.current_input_device() end
function s1.game_input.current_platform_type() end
function s1.game_input.is_typing() end
function s1.game_input.mouse_scroll_delta() end
function s1.game_input.vehicle_drive_axis() end
function s1.game_input.ui_tab_navigation_primary_axis() end
function s1.game_input.ui_tab_navigation_secondary_axis() end
function s1.game_input.ui_tab_navigation_tertiary_axis() end
function s1.game_input.ui_scrollbar_axis() end
function s1.game_input.ui_map_zoom_axis() end
function s1.game_input.ui_modify_amount_increment_tier_one_axis() end
function s1.game_input.ui_modify_amount_increment_tier_two_axis() end
function s1.game_input.ui_modify_amount_increment_tier_three_axis() end

---@class s1_game
s1.game = {}
function s1.game.end_tutorial(natural) end
function s1.game.is_tutorial() end
function s1.game.seed() end

---@class s1_gamepad_pointer
s1.gamepad_pointer = {}
function s1.gamepad_pointer.set_active(value) end
function s1.gamepad_pointer.move_to_screen_center() end
function s1.gamepad_pointer.set_sensitivity(sensitivity) end
function s1.gamepad_pointer.set_aim_assist(value) end
function s1.gamepad_pointer.set_pointer_data(id) end
function s1.gamepad_pointer.revert_pointer_data() end
function s1.gamepad_pointer.set_rotation_input_check_active(active) end
function s1.gamepad_pointer.set_pointer_locked(locked) end
function s1.gamepad_pointer.debug_toggle_active() end
function s1.gamepad_pointer.set_to_snap_handler() end
function s1.gamepad_pointer.is_rotation_input_active() end

---@class s1_gameplay_menu
s1.gameplay_menu = {}
function s1.gameplay_menu.set_screen(screen) end
function s1.gameplay_menu.open() end
function s1.gameplay_menu.close() end
function s1.gameplay_menu.is_open() end
function s1.gameplay_menu.character_screen_enabled() end
function s1.gameplay_menu.current_screen() end

---@class s1_gameplay_menu_interface
s1.gameplay_menu_interface = {}
function s1.gameplay_menu_interface.open() end
function s1.gameplay_menu_interface.close() end
function s1.gameplay_menu_interface.phone_clicked() end
function s1.gameplay_menu_interface.character_clicked() end
function s1.gameplay_menu_interface.set_selected(screen) end

---@class s1_generic_selection_module
s1.generic_selection_module = {}
function s1.generic_selection_module.close() end
function s1.generic_selection_module.cancel() end
function s1.generic_selection_module.is_open() end
function s1.generic_selection_module.chosen_option_index() end

---@class s1_graffiti
s1.graffiti = {}
function s1.graffiti.get_pixel_strength(strokeSize, pixelIndex) end

---@class s1_graffiti_menu
s1.graffiti_menu = {}
function s1.graffiti_menu.open() end
function s1.graffiti_menu.close() end
function s1.graffiti_menu.show_confirm_panel() end
function s1.graffiti_menu.update_remaining_paint_indicator(remainingPaint) end
function s1.graffiti_menu.clear_active_surface() end

---@class s1_handover_screen
s1.handover_screen = {}
function s1.handover_screen.test_open() end
function s1.handover_screen.close(outcome) end
function s1.handover_screen.done_pressed() end
function s1.handover_screen.clear_customer_slots(returnToOriginals) end
function s1.handover_screen.is_open() end

---@class s1_heatmap
s1.heatmap = {}
function s1.heatmap.set_heatmap_active(propertyCode, isActive) end
function s1.heatmap.set_all_heatmaps_active(isActive) end
function s1.heatmap.turn_on_all_heatmaps() end
function s1.heatmap.turn_off_all_heatmaps() end
function s1.heatmap.run_dispatch_heatmap() end

---@class s1_hint_display
s1.hint_display = {}
function s1.hint_display.show_hint_10s(text, alternateText) end
function s1.hint_display.show_hint_20s(text, alternateText) end
function s1.hint_display.show_hint(text, autoCloseTime, alternateText) end
function s1.hint_display.hide() end
function s1.hint_display.queue_hint_10s(message) end
function s1.hint_display.queue_hint_20s(message) end
function s1.hint_display.queue_hint(message, time) end
function s1.hint_display.is_open() end

---@class s1_home_screen
s1.home_screen = {}
function s1.home_screen.set_is_open(o) end
function s1.home_screen.set_canvas_active(a) end
function s1.home_screen.is_open() end

---@class s1_hospital_bill_screen
s1.hospital_bill_screen = {}
function s1.hospital_bill_screen.open() end
function s1.hospital_bill_screen.close() end
function s1.hospital_bill_screen.on_close() end
function s1.hospital_bill_screen.is_open() end

---@class s1_hud
s1.hud = {}
function s1.hud.set_crosshair_visible(vis) end
function s1.hud.set_black_overlay_visible(vis, fadeTime) end
function s1.hud.show_radial_indicator(fill) end
function s1.hud.show_top_screen_text(t) end
function s1.hud.hide_top_screen_text() end
function s1.hud.show_firearm_reticle() end
function s1.hud.hide_firearm_reticle() end
function s1.hud.set_firearm_reticle(spreadAngle) end

---@class s1_icon_creator_canvas
s1.icon_creator_canvas = {}
function s1.icon_creator_canvas.set_taking_picture() end

---@class s1_icon_generator
s1.icon_generator = {}
function s1.icon_generator.generate_icon() end

---@class s1_input_prompts
s1.input_prompts = {}
function s1.input_prompts.get_display_name_for_control_path(controlPath) end
function s1.input_prompts.load_module(id, position, displayTextOverride) end
function s1.input_prompts.unload_module(id) end
function s1.input_prompts.update_display_text_override(panelId, displayTextOverride) end
function s1.input_prompts.show_hide_active_prompt(panelId, show) end
function s1.input_prompts.has_active_prompt(id) end
function s1.input_prompts.debug_load_module() end
function s1.input_prompts.debug_unload_module() end

---@class s1_instancing
s1.instancing = {}
function s1.instancing.enable_instancing() end
function s1.instancing.disable_instancing() end
function s1.instancing.try_assign_camera() end

---@class s1_interaction_canvas
s1.interaction_canvas = {}
function s1.interaction_canvas.set_active(value) end
function s1.interaction_canvas.lerp_display_scale(endScale) end
function s1.interaction_canvas.display_scale() end

---@class s1_interaction
s1.interaction = {}
function s1.interaction.is_anything_blocking_interaction() end
function s1.interaction.set_can_destroy(canDestroy) end
function s1.interaction.can_destroy() end
function s1.interaction.interact_key_str() end

---@class s1_intro
s1.intro = {}
function s1.intro.play() end
function s1.intro.passed_step(stepIndex) end
function s1.intro.is_playing() end

---@class s1_item_ui
s1.item_ui = {}
function s1.item_ui.controller_toggle_tooltip() end
function s1.item_ui.controller_grab_all_slot() end
function s1.item_ui.controller_quick_move_slot() end
function s1.item_ui.controller_quick_move_slot_single() end
function s1.item_ui.controller_drag_add_quantity() end
function s1.item_ui.controller_drag_subtract_quantity() end
function s1.item_ui.controller_discard_slot() end
function s1.item_ui.set_dragging_enabled(enabled) end
function s1.item_ui.disable_quick_move() end
function s1.item_ui.dragging_enabled() end
function s1.item_ui.quick_move_enabled() end
function s1.item_ui.is_currently_dragging() end
function s1.item_ui.is_hovering_slot() end
function s1.item_ui.is_dragging_cash() end

---@class s1_journal_app
s1.journal_app = {}
function s1.journal_app.set_open(open) end

---@class s1_lab_oven_canvas
s1.lab_oven_canvas = {}
function s1.lab_oven_canvas.close() end
function s1.lab_oven_canvas.begin_button_pressed() end
function s1.lab_oven_canvas.can_begin() end

---@class s1_law
s1.law = {}
function s1.law.end_override() end
function s1.law.change_internal_intensity(change) end
function s1.law.set_internal_intensity(intensity) end
function s1.law.override_settings() end

---@class s1_level
s1.level = {}
function s1.level.add_xp(xp) end
function s1.level.get_xp_for_tier(rank) end
function s1.level.rank() end
function s1.level.tier() end
function s1.level.xp() end
function s1.level.total_xp() end
function s1.level.xp_to_next_tier() end

---@class s1_loading_screen
s1.loading_screen = {}
function s1.loading_screen.open(loadingTutorial) end
function s1.loading_screen.close() end
function s1.loading_screen.is_open() end

---@class s1_load
s1.load = {}
function s1.load.get_load_status_text() end
function s1.load.load_tutorial_as_client() end
function s1.load.load_as_client(steamId64) end
function s1.load.set_waiting_for_host_load() end
function s1.load.load_last_save() end
function s1.load.refresh_save_info() end
function s1.load.default_tutorial_save_folder() end
function s1.load.is_in_game_scene() end
function s1.load.is_game_loaded() end
function s1.load.is_loading() end
function s1.load.time_since_game_loaded() end
function s1.load.debug_mode() end
function s1.load.load_status() end
function s1.load.loaded_game_folder_path() end

---@class s1_lobby
s1.lobby = {}
function s1.lobby.try_open_invite_interface() end
function s1.lobby.create_lobby() end
function s1.lobby.leave_lobby() end
function s1.lobby.send_lobby_message(message) end
function s1.lobby.set_lobby_data(key, value) end
function s1.lobby.is_session_ready_for_client() end
function s1.lobby.get_session_connection_identifier() end
function s1.lobby.is_host() end
function s1.lobby.lobby_id() end
function s1.lobby.is_in_lobby() end
function s1.lobby.player_count() end

---@class s1_lobby_interface
s1.lobby_interface = {}
function s1.lobby_interface.set_visible(visible) end
function s1.lobby_interface.leave_clicked() end
function s1.lobby_interface.invite_clicked() end
function s1.lobby_interface.detach_from_screen() end

---@class s1_main_menu_popup
s1.main_menu_popup = {}
function s1.main_menu_popup.open(title, description, isBad) end

---@class s1_management_clipboard
s1.management_clipboard = {}
function s1.management_clipboard.close() end
function s1.management_clipboard.close_and_preserve_state() end
function s1.management_clipboard.is_open() end
function s1.management_clipboard.state_preserved() end

---@class s1_management_interface
s1.management_interface = {}
function s1.management_interface.close(preserveState) end
function s1.management_interface.rename_button_clicked() end

---@class s1_management_worldspace_canvas
s1.management_worldspace_canvas = {}
function s1.management_worldspace_canvas.open() end
function s1.management_worldspace_canvas.close(preserveSelection) end
function s1.management_worldspace_canvas.show_crosshair_prompt(message) end
function s1.management_worldspace_canvas.hide_crosshair_prompt() end
function s1.management_worldspace_canvas.is_open() end

---@class s1_map_app
s1.map_app = {}
function s1.map_app.set_open(open) end

---@class s1_map_position_utility
s1.map_position_utility = {}
function s1.map_position_utility.recalculate() end

---@class s1_messages_app
s1.messages_app = {}
function s1.messages_app.reposition_entries() end
function s1.messages_app.return_button_clicked() end
function s1.messages_app.refresh_notifications() end
function s1.messages_app.filter_by_category(category) end
function s1.messages_app.clear_filter() end
function s1.messages_app.set_open(open) end

---@class s1_messaging
s1.messaging = {}
function s1.messaging.send_response(responseIndex, npcID) end
function s1.messaging.send_player_message(sendableIndex, sentIndex, npcID) end
function s1.messaging.clear_responses(npcID) end

---@class s1_metadata
s1.metadata = {}
function s1.metadata.creation_version() end

---@class s1_mixing_station_interface
s1.mixing_station_interface = {}
function s1.mixing_station_interface.close() end
function s1.mixing_station_interface.begin_button_pressed() end

---@class s1_money
s1.money = {}
function s1.money.create_online_transaction(_transaction_Name, _unit_Amount, _quantity, _transaction_Note) end
function s1.money.change_lifetime_earnings(change) end
function s1.money.play_cash_sound() end
function s1.money.change_cash_balance(change, visualizeChange, playCashSound) end
function s1.money.format_amount(amount, showDecimals, includeColor) end
function s1.money.check_networth_achievements() end
function s1.money.get_net_worth() end
function s1.money.lifetime_earnings() end
function s1.money.last_calculated_networth() end
function s1.money.cash_balance() end

---@class s1_mugshot_generator
s1.mugshot_generator = {}
function s1.mugshot_generator.generate_mugshot() end

---@class s1_mushroom_spawn_station_interface
s1.mushroom_spawn_station_interface = {}
function s1.mushroom_spawn_station_interface.on_begin_button_pressed() end
function s1.mushroom_spawn_station_interface.close() end

---@class s1_music
s1.music = {}
function s1.music.set_music_distorted(distorted, transition) end
function s1.music.set_track_enabled(trackName, enabled) end
function s1.music.stop_track(trackName) end
function s1.music.stop_and_disable_tracks() end
function s1.music.is_any_track_playing() end

---@class s1_new_customer_popup
s1.new_customer_popup = {}
function s1.new_customer_popup.is_playing() end

---@class s1_new_mix_screen
s1.new_mix_screen = {}
function s1.new_mix_screen.close() end
function s1.new_mix_screen.randomize_button_clicked() end
function s1.new_mix_screen.confirm_button_clicked() end
function s1.new_mix_screen.on_name_value_changed(newVal) end
function s1.new_mix_screen.is_open() end

---@class s1_npc_summon_menu
s1.npc_summon_menu = {}
function s1.npc_summon_menu.close() end

---@class s1_occlusion
s1.occlusion = {}
function s1.occlusion.run_occlusion_bake() end
function s1.occlusion.set_active(isActive) end
function s1.occlusion.check_data() end

---@class s1_on_screen_mouse
s1.on_screen_mouse = {}
function s1.on_screen_mouse.activate() end
function s1.on_screen_mouse.deactivate() end

---@class s1_packaging_station_canvas
s1.packaging_station_canvas = {}
function s1.packaging_station_canvas.close() end
function s1.packaging_station_canvas.begin_button_pressed() end
function s1.packaging_station_canvas.repeat_packaging_task() end
function s1.packaging_station_canvas.toggle_mode() end
function s1.packaging_station_canvas.set_mode(mode) end

---@class s1_pause_menu
s1.pause_menu = {}
function s1.pause_menu.pause() end
function s1.pause_menu.resume() end
function s1.pause_menu.stuck_button_clicked() end
function s1.pause_menu.is_paused() end

---@class s1_pawn_shop_interface
s1.pawn_shop_interface = {}
function s1.pawn_shop_interface.open() end
function s1.pawn_shop_interface.close() end
function s1.pawn_shop_interface.start_button_pressed() end
function s1.pawn_shop_interface.set_player_response(response) end
function s1.pawn_shop_interface.accept_or_counter() end
function s1.pawn_shop_interface.cancel() end
function s1.pawn_shop_interface.is_open() end
function s1.pawn_shop_interface.npc_anger() end

---@class s1_phone
s1.phone = {}
function s1.phone.set_is_open(o) end
function s1.phone.set_is_active_gameplay_screen(isActive) end
function s1.phone.set_is_horizontal(h) end
function s1.phone.set_look_offset_multiplier(multiplier) end
function s1.phone.request_close_app() end
function s1.phone.is_open() end
function s1.phone.is_horizontal() end
function s1.phone.is_openable() end
function s1.phone.flashlight_on() end
function s1.phone.is_any_app_open() end
function s1.phone.scaled_look_offset() end

---@class s1_physics
s1.physics = {}
function s1.physics.gravity_multiplier() end

---@class s1_pickpocket_screen
s1.pickpocket_screen = {}
function s1.pickpocket_screen.set_slot_locked(index, locked) end
function s1.pickpocket_screen.close() end
function s1.pickpocket_screen.close_tutorial() end
function s1.pickpocket_screen.is_open() end
function s1.pickpocket_screen.tutorial_open() end

---@class s1_player_camera
s1.player_camera = {}
function s1.player_camera.set_antialiasing_mode(mode) end
function s1.player_camera.apply_aa_settings() end
function s1.player_camera.get_target_local_y() end
function s1.player_camera.set_camera_mode(mode) end
function s1.player_camera.lock_mouse(showCrosshair) end
function s1.player_camera.free_mouse(hideCrosshair) end
function s1.player_camera.stop_transform_override(lerpTime, reenableCameraLook, returnToOriginalRotation) end
function s1.player_camera.set_can_look(canLook) end
function s1.player_camera.set_do_f_active(active, lerpTime) end
function s1.player_camera.override_fov(fov, lerpTime) end
function s1.player_camera.stop_fov_override(lerpTime) end
function s1.player_camera.add_active_ui_element(name) end
function s1.player_camera.remove_active_ui_element(name) end
function s1.player_camera.jolt_camera() end
function s1.player_camera.is01(a) end
function s1.player_camera.reset_rotation() end
function s1.player_camera.stop_focus() end
function s1.player_camera.start_camera_shake(intensity, duration, decreaseOverTime) end
function s1.player_camera.stop_camera_shake() end
function s1.player_camera.update_camera_bob() end
function s1.player_camera.set_free_cam(enable, reenableLook) end
function s1.player_camera.anti_aliasing_mode() end
function s1.player_camera.can_look() end
function s1.player_camera.active_ui_element_count() end
function s1.player_camera.free_cam_enabled() end
function s1.player_camera.viewing_avatar() end
function s1.player_camera.camera_mode() end
function s1.player_camera.meth_visuals() end
function s1.player_camera.cocaine_visuals() end
function s1.player_camera.fov_jitter() end

---@class s1_player_inventory
s1.player_inventory = {}
function s1.player_inventory.set_inventory_enabled(enabled) end
function s1.player_inventory.set_equipping_enabled(enabled) end
function s1.player_inventory.detach_from_screen() end
function s1.player_inventory.set_management_clipboard_enabled(enabled) end
function s1.player_inventory.set_viewmodel_visible(visible) end
function s1.player_inventory.get_amount_of_item(ID) end
function s1.player_inventory.remove_amount_of_item(ID, amount) end
function s1.player_inventory.clear_inventory() end
function s1.player_inventory.remove_product_from_inventory(maxStealth) end
function s1.player_inventory.remove_random_items_from_inventory() end
function s1.player_inventory.equipped_slot_changed() end
function s1.player_inventory.reequip() end
function s1.player_inventory.equipped_slot_index() end
function s1.player_inventory.hotbar_enabled() end
function s1.player_inventory.equipping_enabled() end
function s1.player_inventory.holster_enabled() end
function s1.player_inventory.current_equip_time() end
function s1.player_inventory.is_anything_equipped() end

---@class s1_player
s1.player = {}
function s1.player.all_player_files_loaded() end
function s1.player.are_all_players_ready_to_sleep() end

---@class s1_player_movement
s1.player_movement = {}
function s1.player_movement.warp_to_nav_mesh(clearVelocity) end
function s1.player_movement.jump() end
function s1.player_movement.set_crouched(c) end
function s1.player_movement.change_stamina(change, notify) end
function s1.player_movement.set_stamina(value, notify) end
function s1.player_movement.add_sprint_blocker(tag) end
function s1.player_movement.remove_sprint_blocker(tag) end
function s1.player_movement.dismount_ladder() end
function s1.player_movement.can_move() end
function s1.player_movement.can_jump() end
function s1.player_movement.is_jumping() end
function s1.player_movement.time_airborne() end
function s1.player_movement.time_grounded() end
function s1.player_movement.is_grounded() end
function s1.player_movement.is_crouched() end
function s1.player_movement.standing_scale() end
function s1.player_movement.is_ragdolled() end
function s1.player_movement.is_sprinting() end
function s1.player_movement.force_sprint() end
function s1.player_movement.current_stamina_reserve() end
function s1.player_movement.current_sprint_multiplier() end
function s1.player_movement.is_on_ladder() end
function s1.player_movement.move_speed_multiplier() end

---@class s1_post_processing
s1.post_processing = {}
function s1.post_processing.override_vignette(intensity, smoothness) end
function s1.post_processing.reset_vignette() end
function s1.post_processing.set_god_ray_intensity(intensity) end
function s1.post_processing.set_contrast(value) end
function s1.post_processing.set_saturation(value) end
function s1.post_processing.set_bloom_threshold(threshold) end
function s1.post_processing.set_blur(blurLevel) end
function s1.post_processing.set_psychedelic_effect_active(isActive) end
function s1.post_processing.print_value_of_psychedelic_effect_blend() end

---@class s1_product
s1.product = {}
function s1.product.set_meth_discovered() end
function s1.product.set_cocaine_discovered() end
function s1.product.set_shrooms_discovered() end
function s1.product.set_product_listed(productID, listed) end
function s1.product.set_product_favourited(productID, listed) end
function s1.product.discover_product(productID) end
function s1.product.set_is_accepting_order(accepting) end
function s1.product.send_mix_recipe(product, mixer, output) end
function s1.product.send_price(productID, value) end
function s1.product.finish_and_name_mix(productID, ingredientID, mixName) end
function s1.product.make_id_file_safe(id) end
function s1.product.is_mix_name_valid(mixName) end
function s1.product.meth_discovered() end
function s1.product.cocaine_discovered() end
function s1.product.shrooms_discovered() end
function s1.product.is_accepting_orders() end
function s1.product.is_mixing_in_progress() end
function s1.product.is_mix_complete() end
function s1.product.time_since_product_listing_changed() end

---@class s1_product_manager_app
s1.product_manager_app = {}
function s1.product_manager_app.set_open(open) end
function s1.product_manager_app.move_to_details_panel() end

---@class s1_progress_slider
s1.progress_slider = {}
function s1.progress_slider.show_progress(progress) end

---@class s1_property
s1.property = {}
function s1.property.delete_unapproved_files(parentFolderPath) end

---@class s1_quest
s1.quest = {}
function s1.quest.send_quest_action(guid, action) end
function s1.quest.send_quest_state(guid, state) end
function s1.quest.send_quest_entry_state(guid, entryIndex, state) end
function s1.quest.print_quest_states() end
function s1.quest.play_complete_quest_sound() end
function s1.quest.play_complete_quest_entry_sound() end

---@class s1_region_unlocked_canvas
s1.region_unlocked_canvas = {}
function s1.region_unlocked_canvas.queue_unlocked(_region) end
function s1.region_unlocked_canvas.start_event() end
function s1.region_unlocked_canvas.end_event() end
function s1.region_unlocked_canvas.is_running() end
function s1.region_unlocked_canvas.order() end

---@class s1_registry
s1.registry = {}
function s1.registry.item_exists(ID) end
function s1.registry.remove_runtime_items() end
function s1.registry.log_ordered_unlocks() end

---@class s1_replication_queue
s1.replication_queue = {}
function s1.replication_queue.get_replication_duration(approximateSizeBytes) end
function s1.replication_queue.replication_done_for_local_player() end
function s1.replication_queue.local_player_replication_timed_out() end
function s1.replication_queue.current_replication_task() end

---@class s1_rtb_interface
s1.rtb_interface = {}
function s1.rtb_interface.close() end

---@class s1_save_manager
s1.save_manager = {}
function s1.save_manager.report_save_error() end
function s1.save_manager.check_save_folder_initialized() end
function s1.save_manager.has_write_permission_on_dir(path) end
function s1.save_manager.save() end
function s1.save_manager.strip_extensions(filePath) end
function s1.save_manager.make_file_safe(fileName) end
function s1.save_manager.get_version_number(version) end
function s1.save_manager.sanitize_file_name(fileName) end
function s1.save_manager.access_permission_issue_detected() end
function s1.save_manager.is_saving() end
function s1.save_manager.seconds_since_last_save() end
function s1.save_manager.players_save_path() end
function s1.save_manager.individual_saves_container_path() end
function s1.save_manager.backup_folder_path() end
function s1.save_manager.save_name() end

---@class s1_settings
s1.settings = {}
function s1.settings.reload_graphics_settings() end
function s1.settings.reload_audio_settings() end
function s1.settings.reload_input_settings() end
function s1.settings.reload_other_settings() end
function s1.settings.reload_gamepad_settings() end
function s1.settings.restore_default_keyboard_bindings() end
function s1.settings.restore_default_gamepad_bindings() end
function s1.settings.get_action_control_path(actionName) end
function s1.settings.christmas_event_active() end
function s1.settings.pausing_freezes_time() end
function s1.settings.unit_type() end
function s1.settings.look_sensitivity() end

---@class s1_sewer_camera_presense
s1.sewer_camera_presense = {}
function s1.sewer_camera_presense.camera_presence_in_sewer_area() end
function s1.sewer_camera_presense.smoothed_camera_presence_in_sewer_area() end

---@class s1_sewer
s1.sewer = {}
function s1.sewer.set_sewer_unlocked_server() end
function s1.sewer.set_random_world_key_collected() end
function s1.sewer.is_sewer_unlocked() end
function s1.sewer.is_random_world_key_collected() end
function s1.sewer.random_sewer_key_location_index() end
function s1.sewer.has_sewer_king_been_defeated() end
function s1.sewer.random_sewer_possessor_index() end

---@class s1_shop
s1.shop = {}
function s1.shop.send_stock(shopCode, itemID, stock) end

---@class s1_sleep_canvas
s1.sleep_canvas = {}
function s1.sleep_canvas.open_menu() end
function s1.sleep_canvas.queue_sleep_message(message, displayTime) end
function s1.sleep_canvas.is_menu_open() end
function s1.sleep_canvas.queued_sleep_message() end

---@class s1_storage_menu
s1.storage_menu = {}
function s1.storage_menu.close() end
function s1.storage_menu.is_open() end

---@class s1_task
s1.task = {}
function s1.task.play_task_complete_sound() end
function s1.task.end_task() end
function s1.task.is_task_active() end
function s1.task.time_on_last_task_end() end

---@class s1_text_input_screen
s1.text_input_screen = {}
function s1.text_input_screen.submit() end
function s1.text_input_screen.cancel() end
function s1.text_input_screen.is_open() end

---@class s1_time
s1.time = {}
function s1.time.set_time_and_sync(time) end
function s1.time.is_current_time_within_range(min, max) end
function s1.time.get_total_min_sum() end
function s1.time.set_time_speed_multiplier(multiplier) end
function s1.time.set_cycle_duration(time) end
function s1.time.start_sleep() end
function s1.time.set_host_sleep_done(done) end
function s1.time.is_given_time_within_range(givenTime, min, max) end
function s1.time.is_valid24_hour_time(input) end
function s1.time.get12_hour_time(_time, appendDesignator) end
function s1.time.get24_hour_time_from_min_sum(minSum) end
function s1.time.get_min_sum_from24_hour_time(_time) end
function s1.time.get_minutes_to_display_time(minutes) end
function s1.time.add_minutes_to24_hour_time(time, minsToAdd) end
function s1.time.minute_duration() end
function s1.time.default_time() end
function s1.time.current_time() end
function s1.time.current_day() end
function s1.time.elapsed_days() end
function s1.time.is_end_of_day() end
function s1.time.is_night() end
function s1.time.normalized_time_of_day() end
function s1.time.day_index() end
function s1.time.is_sleep_in_progress() end
function s1.time.playtime() end
function s1.time.host_sleep_done() end
function s1.time.time_speed_multiplier() end
function s1.time.daily_min_sum() end

---@class s1_tooltip
s1.tooltip = {}
function s1.tooltip.hide_tooltip() end

---@class s1_trash_bag_canvas
s1.trash_bag_canvas = {}
function s1.trash_bag_canvas.open() end
function s1.trash_bag_canvas.close() end
function s1.trash_bag_canvas.is_open() end

---@class s1_trash
s1.trash = {}
function s1.trash.destroy_all_trash() end

---@class s1_ui_screen
s1.ui_screen = {}
function s1.ui_screen.is_active_screen_registered_for_back() end
function s1.ui_screen.is_any_screen_active() end
function s1.ui_screen.is_any_popup_screen_active() end
function s1.ui_screen.open_popup_screen(popupID) end
function s1.ui_screen.close_popup_screen(popupID) end
function s1.ui_screen.has_active_screen() end
function s1.ui_screen.is_back_triggered_this_frame() end

---@class s1_variable_database
s1.variable_database = {}
function s1.variable_database.set_variable_value(variableName, value, network) end
function s1.variable_database.print_all_variables() end
function s1.variable_database.print_variable_value(variableName) end
function s1.variable_database.notify_item_acquired(id, quantity) end

---@class s1_vehicle_colors
s1.vehicle_colors = {}
function s1.vehicle_colors.get_color_name(c) end

---@class s1_vehicle_mod_menu
s1.vehicle_mod_menu = {}
function s1.vehicle_mod_menu.close() end
function s1.vehicle_mod_menu.color_clicked(col) end
function s1.vehicle_mod_menu.confirm_button_clicked() end
function s1.vehicle_mod_menu.is_open() end

---@class s1_viewmodel_avatar
s1.viewmodel_avatar = {}
function s1.viewmodel_avatar.set_visibility(isVisible) end
function s1.viewmodel_avatar.is_visible() end

---@class s1_viewmodel_sway
s1.viewmodel_sway = {}
function s1.viewmodel_sway.refresh_viewmodel() end

