<#
    Freeze-Surface.ps1 - friert die HEUTIGE erzeugte Flaeche als Messlatte ein.

    WARUM ES DAS GIBT
    Die s1-Flaeche soll kuenftig beim NUTZER entstehen statt bei uns einkompiliert zu werden.
    Jeder Schritt dorthin muss gegen etwas gemessen werden, das sich nicht mitverschiebt -
    sonst beweist man nur, dass zwei Fassungen desselben Irrtums uebereinstimmen.

    ⚠ EIN MD5 DER .g.cs GENUEGT DAFUER NICHT. Er beweist die DATEI, nicht die MENGE: eine
    umsortierte oder anders formatierte Erzeugung hat einen anderen Hash und dieselbe Flaeche -
    und umgekehrt kann eine gleich grosse Flaeche andere Member binden. Verglichen wird deshalb
    ueber MENGEN von Paaren (Tabelle, Lua-Name, CLR-Ziel), nicht ueber Text.

    Die Datei surface\abnahme.txt ist ab jetzt die Abnahmegrundlage. Sie wird versioniert,
    damit ein spaeterer Lauf gegen den Stand von heute pruefen kann und nicht gegen sich selbst.

    AUFRUF
        .\tools\Freeze-Surface.ps1            schreibt surface\abnahme.txt
        .\tools\Freeze-Surface.ps1 -Pruefen   vergleicht die aktuelle .g.cs dagegen
#>
[CmdletBinding()]
param(
    [string] $Wurzel,
    [switch] $Pruefen
)
$ErrorActionPreference = 'Stop'

if (-not $Wurzel) { $Wurzel = Split-Path $PSScriptRoot -Parent }
$quelle = Join-Path $Wurzel 'Host\Generated\GeneratedSurface.g.cs'
$ziel   = Join-Path $Wurzel 'surface\abnahme.txt'

if (-not (Test-Path $quelle)) { Write-Host "  ABORT: not found: $quelle" -ForegroundColor Red; exit 1 }

# ---- Aus dem erzeugten C# die Paarliste ziehen.
# Aufbau je Tabelle:   var t = new Table(script); ... s1.Set("<tabelle>", ...)
# Aufbau je Eintrag:   t.Set("<lua>", DynValue.NewCallback((c, a) => { ... S1I_<X>.Instance.<Member> ... }))
$zeilen = Get-Content $quelle
$tabelle = '?'
$eintraege = New-Object System.Collections.Generic.List[string]
$tabellen  = New-Object System.Collections.Generic.List[string]

foreach ($z in $zeilen) {
    # Die Tabellenzeile kommt NACH ihren Eintraegen - deshalb wird sie rueckwirkend gesetzt.
    if ($z -match 's1\.Set\("([^"]+)"') {
        $name = $Matches[1]
        $tabellen.Add($name)
        for ($i = $eintraege.Count - 1; $i -ge 0; $i--) {
            if ($eintraege[$i] -like '?|*') { $eintraege[$i] = $name + $eintraege[$i].Substring(1) }
            else { break }
        }
        continue
    }
    if ($z -notmatch 't\.Set\("([^"]+)"') { continue }
    $lua = $Matches[1]

    # Das CLR-Ziel: der erste Zugriff auf einen Alias, statisch oder ueber .Instance.
    $ziel1 = ''
    if ($z -match '(S1[IT]_[A-Za-z0-9_]+)\.Instance\.([A-Za-z_][A-Za-z0-9_]*)') {
        $ziel1 = $Matches[1] + '.Instance.' + $Matches[2]
    } elseif ($z -match '(S1[IT]_[A-Za-z0-9_]+)\.([A-Za-z_][A-Za-z0-9_]*)') {
        $ziel1 = $Matches[1] + '.' + $Matches[2]
    }
    # Art: Aufruf mit Klammern = Methode, sonst Wert.
    $art = if ($z -match [regex]::Escape($ziel1) + '\s*\(') { 'call' } else { 'value' }
    # Argumentzahl grob aus den a[n]-Zugriffen der Zeile.
    $argn = ([regex]::Matches($z, 'a\[(\d+)\]') | ForEach-Object { [int]$_.Groups[1].Value } |
             Measure-Object -Maximum).Maximum
    if ($null -eq $argn) { $argn = -1 }
    $eintraege.Add('?|' + $lua + '|' + $ziel1 + '|' + $art + '|' + ($argn + 1))
}

$fertig = @($eintraege | Where-Object { $_ -notlike '?|*' } | Sort-Object)
$offen  = @($eintraege | Where-Object { $_ -like '?|*' })

if ($Pruefen) {
    if (-not (Test-Path $ziel)) { Write-Host "  ABORT: no baseline yet - run without -Pruefen first." -ForegroundColor Red; exit 1 }
    $alt = @(Get-Content $ziel | Where-Object { $_ -and $_ -notlike '#*' } | Sort-Object)
    $d = Compare-Object $alt $fertig
    if (-not $d) {
        Write-Host ("  unchanged: {0} entries in {1} tables" -f $fertig.Count, $tabellen.Count) -ForegroundColor Green
        exit 0
    }
    Write-Host "  SURFACE CHANGED against surface\abnahme.txt:" -ForegroundColor Red
    foreach ($x in $d) { Write-Host ("    {0} {1}" -f $x.SideIndicator, $x.InputObject) }
    exit 1
}

$kopf = @(
    "# ScriptOne - the surface as it is TODAY, frozen as a yardstick.",
    "# Generated by tools\Freeze-Surface.ps1 from Host\Generated\GeneratedSurface.g.cs",
    "# Format: <table>|<lua name>|<clr target>|call|value|<arg count>",
    "# Do not edit. Regenerate only when the surface is MEANT to change.",
    ("# tables: {0}   entries: {1}" -f $tabellen.Count, $fertig.Count)
)
$ordner = Split-Path $ziel -Parent
if (-not (Test-Path $ordner)) { New-Item -ItemType Directory -Path $ordner -Force | Out-Null }
Set-Content -Path $ziel -Value ($kopf + $fertig) -Encoding UTF8

Write-Host ("  frozen: {0} entries in {1} tables -> {2}" -f $fertig.Count, $tabellen.Count, $ziel) -ForegroundColor Green
if ($offen.Count -gt 0) {
    Write-Host ("  WARNING: {0} entries could not be assigned to a table" -f $offen.Count) -ForegroundColor Yellow
    exit 1
}
exit 0
